version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Demo-API"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-has1esngssfk"
s3_prefix = "Demo-API"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "ENV=prod AllowPayment=1 "